version: '3.8'

# Define services
services:

  mysqldatabase:
    image: mysql/mysql-server:latest
    container_name: mykid-mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: mykiddb
      MYSQL_USER: root
      MYSQL_PASSWORD: mykid
      MYSQL_ROOT_PASSWORD: mykid
    networks:
      - mykid

  nginx:
    image: nginx:latest
    container_name: mykid-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/logs/nginx
    ports:
      - 80:80
      - 443:443

  mykid-service:
    image: mykid-service:0.0.1
    container_name: mykid-service
    depends_on:
      - mysqldatabase
    ports:
      - "2021:2021"
    networks:
      - mykid
    environment: # Pass environment variables to the service
      JASYPT_ENCRYPTOR_PASSWORD: mykid_key
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldatabase:3306/mykiddb?serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: mykid
      SPRING_DATASOURCE_PASSWORD: mykid

networks:
  mykid: