spring:
  application:
    name: mykid-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    database: mysql
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

  datasource:
#    url: jdbc:mysql://localhost:3306/mykiddb?serverTimezone=UTC&useLegacyDatetimeCode=false
    url: ENC(uX5x03yJ3L9P2vq7GXp49i30ep3/0BqoKea11BdklnWy2MYW3JCODmKSsXb+U7BLkCFvU0/B67thN7guVzPU19CR5TsmVl2OCwWwHwXY+u1RUUK5Kq1xOT1USAgdyrRxCccnAVMwCcTgwyJDPeC0l9H7d2aGSpUbunaSJsKxIQc=)
    username: root
    password: ENC(PJSkKwOqGxR3BCcY64OdVyaMiVMlqOhUtJaI/4aGI1U5adDuhBSgfHSgtH8UkLvu)
    hikari:
      maximum-pool-size: 3

logging:
  level:
    root: INFO

server:
  port: 2021

jasypt:
  encryptor:
    password: mykid_key