version: '3.8'

# Define services
services:

  mysqldatabase:
    image: mysql/mysql-server:latest
    container_name: mykid-mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: mykiddb
      MYSQL_USER: root
      MYSQL_PASSWORD: mykid
      MYSQL_ROOT_PASSWORD: mykid
    networks:
      - database

  nginx:
    image: nginx:latest
    container_name: mykid-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/logs/nginx
    ports:
      - 80:80
      - 443:443

networks:
  database: