openapi: 3.0.3
info:
  title: mykid
  description: "a funny application that groups together stats for your baby"
  termsOfService: todo
  contact:
    email: todo@todo.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1-SNAPSHOT
tags:
  - name: my-kid
    description: my kid

paths:

  /api/v1/stats:
    get:
      operationId: getStats
      tags:
        - my-kid
      responses:
        '200':
          description: all the stats available in the given interval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStatsResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: postStat
      tags:
        - my-kid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stats'
      responses:
        '200':
          description: the stat record was saved
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/stats-daily:
    get:
      operationId: getDailyStats
      tags:
        - my-kid
      parameters:
        - in: query
          name: history
          schema:
            type: string
            enum:
              - today
              - yesterday
              - last24h
              - last48h
              - last72h
              - last7d
              - last1m
              - last3m
              - alltime

      responses:
        '200':
          description: stats summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDailyStatsResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/stats/del-stat:
    post:
      operationId: deleteStat
      tags:
        - my-kid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stats'
      responses:
        '200':
          description: the sleep record was deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/auth/signup:
    post:
      tags:
        - user
      summary: Create a user
      description: Create a user
      operationId: signup
      requestBody:
        description: Create a user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-codegen-request-body-name: body

  /api/v1/auth/login:
    post:
      tags:
        - user
      summary: Use it to login
      description: Use it to login
      operationId: login
      requestBody:
        description: Use it to login
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-codegen-request-body-name: body

  /api/v1/sleep:
    get:
      operationId: getSleep
      tags:
        - my-kid
      responses:
        '200':
          description: sleep records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSleepResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: saveSleep
      tags:
        - my-kid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sleep'
      responses:
        '200':
          description: the stat record was saved
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/sleep-daily:
    get:
      operationId: getDailySleep
      tags:
        - my-kid
      responses:
        '200':
          description: sleep summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDailySleepResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/sleep/del-sleep:
    post:
      operationId: deleteSleep
      tags:
        - my-kid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sleep'
      responses:
        '200':
          description: the sleep record was deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:

    GetDailySleepResponse:
      type: object
      properties:
        dailySleepEntries:
          type: array
          items:
            $ref: '#/components/schemas/DailySleep'
    DailySleep:
       type: object
       properties:
         date:
           type: string
         totalSleep:
           type: number
           format: double
    GetSleepResponse:
      type: object
      properties:
        sleepEntries:
          type: array
          items:
            $ref: '#/components/schemas/Sleep'
    Sleep:
      type: object
      properties:
        token:
          type: string
        createdAt:
          type: string
          format: date-time
        sleepStart:
          type: string
          format: date-time
        sleepEnd:
          type: string
          format: date-time

    GetStatsResponse:
      type: object
      properties:
        statsEntries:
          type: array
          items:
            $ref: '#/components/schemas/Stats'
    Stats:
      type: object
      required:
        - createdAt
        - datetime
      properties:
        token:
          type: string
        datetime:
          type: string
          format: date-time
        activities:
          type: array
          items:
            $ref: '#/components/schemas/GenericActivities'
        temperature:
          type: number
          format: double
        feedFromLeftDuration:
          type: number
          format: double
        feedFromRightDuration:
          type: number
          format: double
        pumpFromLeftQuantity:
          type: number
          format: double
        pumpFromRightQuantity:
          type: number
          format: double
        extraBottleMotherMilkQuantity:
          type: number
          format: double
        extraBottleFormulaeMilkQuantity:
          type: number
          format: double
        weight:
          type: number
          format: double
        createdAt:
          type: string
          format: date-time
        daycount:
          type: integer
          format: int32
    GetDailyStatsResponse:
      type: object
      properties:
        dailyStatsEntries:
          type: array
          items:
            $ref: '#/components/schemas/DailyStat'
    DailyStat:
      type: object
      properties:
        date:
          type: string
        dailyFeedQuantity:
          type: number
          format: double
        weight:
          type: number
          format: double
        dailyFeedTime:
          type: number
          format: double
        activities:
          type: array
          items:
            $ref: '#/components/schemas/GenericActivities'


    GenericActivities:
      type: string
      enum:
        - BREAST_MILK
        - BOTTLE_MOTHER_MILK
        - BOTTLE_FORMULAE_MILK
        - WEIGHT
        - PUMP
        - SPIT
        - URINE
        - POOP
        - VITAMIN_D
        - VITAMIN_K
        - BONNISAN
        - TEMPERATURE

    User:
      type: object
      required:
        - username
      properties:
        token:
          type: string
        username:
          type: string
        password:
          type: string
        email:
          type: string
        createdAt:
          type: string
          format: date-time
        jwtToken:
          type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string