CREATE TABLE db_kid_stats (
      ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
    , DATETIME DATETIME
    , ACTIVITIES VARCHAR (400)
    , TEMP DECIMAL(4, 2)
    , FFL_DUR DECIMAL(6, 2)
    , FFR_DUR DECIMAL(6, 2)
    , PFL_QTY DECIMAL(6, 2)
    , PFR_QTY DECIMAL(6, 2)
    , WEIGHT DECIMAL(6, 2)
    , EXTRA_M_QTY DECIMAL(6, 2)
    , EXTRA_F_QTY DECIMAL(6, 2)
    , CREATED_AT DATETIME
    , INDEX (CREATED_AT)
    , INDEX (DATETIME)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8MB4;