CREATE TABLE db_kid_user (
      ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
    , USERNAME VARCHAR (100)
    , EMAIL VARCHAR (100)
    , PASSWORD VARCHAR (100)
    , CREATED_AT DATETIME
    , INDEX (USERNAME)
    , INDEX (CREATED_AT)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8MB4;